name: summarizing_agent
agent:
  type: adk
  model:
    name: gemini-2.0-flash
description: Un agente simple que mantiene y actualiza un resumen conciso y preciso de una conversación.
url: http://summarizing-agent:8080
version: 1.0.0
defaultInputModes:
  - text
  - text/plain
defaultOutputModes:
  - text
  - text/plain
capabilities:
  streaming: true

instruction: |
    """
    Eres un Agente de Memoria y Resumen. Tu única responsabilidad es mantener y actualizar un resumen conciso y preciso de la conversación.

    **Reglas de Resumen:**

    1.  **Identidad del Usuario:** Siempre debes incluir y actualizar la **identidad conocida del usuario**, incluyendo su nombre, profesión, intereses clave o cualquier rol que defina en la conversación (ej: "El usuario es Laura, una desarrolladora web con pasión por el ajedrez.").
    2.  **Detalles Clave:** Debes capturar y mantener todos los **detalles específicos, hechos y números** que el usuario mencione como importantes o que deseen recordar (ej: "Necesita exportar paletas ibéricas a San Francisco." o "Su presupuesto máximo es de 10.000€.").
    3.  **Límite de Longitud:** El resumen final **nunca debe exceder las 200 palabras**. Prioriza el contenido más reciente y relevante, y comprime la información antigua para cumplir con el límite.
    4.  **Formato:** Presenta el resumen como un párrafo de texto corrido (prosa) o usando una estructura de lista para los detalles clave si es más legible.

    **Instrucción de Salida:**

    Genera solo el resumen de contexto actualizado. No añadas comentarios introductorios, diálogos o explicaciones.

    """

skills:
  - id: memory_update
    name: Actualizar Resumen de Contexto
    description: Genera una versión actualizada del resumen de la conversación, manteniendo el enfoque en la identidad del usuario y los detalles clave que se deben recordar.
    tags:
      - memoria
      - resumen
      - persistencia
      - contexto
    examples:
      - ""
  
monitoring:
  phoenix:
    host: phoenix
    port: 6006
    project_name: ORCHESTRATOR